# Don't change
config-version: '16'

# chinese/english/spanish
lang: english

# Worlds where fishing mechanic takes effects
# 启用本插件的世界
worlds:
  # Mode: whitelist/blacklist
  # 模式：白名单/黑名单
  mode: whitelist
  list:
    - world
    - world_nether

# Mechanic settings
mechanics:
  # Add custom nbt tags to the loots so plugin could identify
  # Disable this will lose the trigger actions when eating fish
  # 为每个战利品增加特殊的CustomFishing NBT标签以被插件识别
  # 禁用此项目将会导致吃食物触发的动作失效
  add-custom-fishing-tags-to-loots: true
  # Disable the fishing bar totally
  # 关闭捕鱼条
  disable-bar-mechanic: false
  # Does the fishing bar show up instantly when the fish is hooked
  # [Note] In this mode, vanilla loots are not available unless you add them to the loot system!
  # 是否在鱼咬钩后立刻显示捕鱼条，而不是需要右键后才显示
  # 注意：启用本设置会导致无法获取原版钓鱼战利品
  instant-bar: false
  # other loots
  # 其他战利品
  other-loots:
    # Should other loots have the same fishing mechanic CustomFishing provides
    # 其他战利品是否有插件提供的钓鱼特性
    fishing-bar: true
    # 原版战利品
    vanilla:
      enable: true
      # 0.4 means 40% of the loots are from vanilla and 60% are from CustomFishing Loot system
      # if there's no custom loot, it would definitely be a vanilla loot
      # 0.4代表40%的战利品来自于原版，60%来自CustomFishing物品库
      # 如果钓鱼的地方没有自定义战利品，那么下一个一定是原版战利品
      ratio: 0.4
    mcMMO:
      # mcMMO treasure system
      # chance represents the chance to try to be a mcMMO treasure
      # But it doesn't mean 50% chance of the loot would be mcMMO treasure
      # mcMMO has a complex treasure system
      # mcMMO宝藏系统
      # 概率代表尝试变成mcMMO宝藏的概率，但这不意味着50%概率一定会变成mcMMO宝藏
      enable: false
      chance: 0.5
  # Does the special fishing mechanic requires special rod
  # 是否需要特殊鱼竿才能体验钓鱼机制
  need-special-rod-to-fish: false
  # Does the CustomFishing loots requires special rod
  # 是否需要特殊鱼竿才能获取钓鱼插件物品库的内容
  need-special-rod-for-loots: false
  # Do all the rods have the ability to fish in lava
  # 任何鱼竿都能在岩浆中钓鱼吗
  all-rods-fish-in-lava: false
  # Does rod lose durability when player successfully fish
  # 钓鱼成功后是否消耗耐久度
  rod-lose-durability: true
  # Competition
  # 钓鱼比赛
  fishing-competition:
    enable: true
    # Enable redis server to sync data between servers
    # 启用Redis服务器以跨服同步比赛数据
    redis: false
  # Fishing bag is a place where players can store their baits, utils, rods (Fish optional)
  # 渔具袋是玩家存放鱼饵，实用道具，鱼竿的地方，其中的鱼饵会在钓鱼时被消耗
  fishing-bag:
    enable: true
    # Fishing bag window title
    # 渔具袋的容器标题
    bag-title: '<blue>{player}''s Fishing Bag'
    # Can fishing bag store the loots? (Requires add-custom-fishing-tags-to-loots: true)
    # 渔具袋是否能存储钓鱼战利品(需要设置add-custom-fishing-tags-to-loots: true)
    can-store-loot: false
    # Other whitelist-items
    # 允许放入渔具袋的其他物品白名单
    whitelist-items:
      - fishing_rod
  # Lava fishing settings
  # 岩浆钓鱼设置
  lava-fishing:
    # ticks
    min-wait-time: 100
    max-wait-time: 600
  # Splash effect when the bobber falls into water
  # 鱼钩落水时的水花飞溅效果
  splash-animation:
    water:
      enable: true
      # config the item in utils
      item: water_effect
      # ticks
      time: 25
    lava:
      enable: true
      item: lava_effect
      # ticks
      time: 25

titles:
  success:
    title:
      - '<green>GG!</green>'
      - '<green>Good Job!</green>'
    subtitle:
      - 'You caught a {loot}'
      - 'Whoa! Nice catch!'
      - 'Oh {loot} here we go!'
      - 'Let''s see what it is!'
    fade:
      # ticks
      in: 10
      stay: 30
      out: 10
  failure:
    title:
      - '<red>Be concentrated!</red>'
      - '<red>What a pity!</red>'
      - '<red>Try next time!</red>'
      - '<red>Bad luck</red>'
    subtitle:
      - 'The fish escaped...'
    fade:
      in: 10
      stay: 30
      out: 10

# Other settings
other-settings:
  # MONITOR HIGHEST HIGH NORMAL LOW LOWEST
  # 事件优先级
  event-priority: NORMAL
  # If enabled, players would not be able to get job exp in vanilla way
  # 如果启用，玩家则无法通过原版方式获得Jobs经验
  disable-JobsReborn-fishing-exp: false
  # Convert MMOItems' rod into CustomFishing's rod
  # keep the same key name both in MMOItems and CustomFishing so rods can extend the bonus of those in CustomFishing
  # 将MMOItems中的鱼竿转换为CustomFishing的鱼竿，只需要保持相同的键名即可继承效果
  convert-MMOItems-rods: false
  # Prevent other players to pick up your fishing loot
  # This is useful for players to fish in a public area
  # 防止其他玩家抢夺捕鱼战利品
  prevent-other-players-pick-up-loot: false
  # Log the money player get from selling the fish in the console
  # 后台记录玩家销售鱼类所得金额
  log-earnings: true
  # Set the MMOCore profession name
  MMOCore-profession-name: 'customfishing'
  # Set the offset characters' unicodes
  # 设置左右偏移字符的unicode
  offset-characters:
    font: customfishing:offset_chars
    '1': 
    '2': 
    '4': 
    '8': 
    '16': 
    '32': 
    '64': 
    '128': 
    '-1': 
    '-2': 
    '-4': 
    '-8': 
    '-16': 
    '-32': 
    '-64': 
    '-128': 